[build]
  command = "echo 'Using pre-built deploy folder'"
  publish = "deploy"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Removed: functions = "netlify/functions"
# Removed: commented out [dev] section
# Removed: commented out additional redirects