name: GitHub Pages Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  package:
    runs-on: ubuntu-latest
    container:
      image: wonderlandengine/editor:latest
    steps:
    - name: Install Git
      run: apt-get update && apt-get install -y git git-lfs
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Debug Environment
      run: |
        echo "Environment Information"
        uname -a
        lsb_release -a
        df -h
        free -m
    - name: Check Disk Space
      run: df -h
    - name: Check Memory
      run: free -m
    - name: Check Docker Version
      run: docker --version
    - name: List Files in Working Directory
      run: ls -al
    - name: Package
      run: WonderlandEditor --windowless --package --project Golf.wlp --output ./public/
      env:
        WLE_CREDENTIALS: ${{ secrets.WLE_CREDENTIALS }}
    - name: List Files for Debugging
      run: ls -l ./public
    - name: Gzip
      run: find ./public/ -type f ! -name '*.gz' -exec gzip -k "{}" \;
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./public

  deploy-pages:
    needs: package
    runs-on: ubuntu-latest
    if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
